### ISSUE TITLE
Fix header style and use Century Gothic font

### ISSUE THREAD

**Issue by FHFHockey-dev** [FHFHockey-dev/fhfhockey.com#10]
Use **Century Gothic** in the following elements:

- [x] post title and post summary
- [x] branding and the page title

> Header should have a white border-bottom and FIVE HOLE is black while FANTASY HOCKEY is white.

- [x] The same highlight class should be applied to mobile UI as well
- [x] Update the `Banner` component for social medias

**Comment by xiaohai-huang** [comment]
For PC view:
- the style of page title (e.g., FHFH BLOG, FHFH LIBRARY) should look like this image. 
- use the new PC header

![image](https://user-images.githubusercontent.com/56380096/179357353-23fdf6e2-4897-472b-b27e-84fdbfd239ae.png)
