### ISSUE TITLE
Apply "snowflake" style to Category Coverage Chart

### ISSUE THREAD

**Issue by FHFHockey-dev** [FHFHockey-dev/fhfhockey.com#20]
Replace the current chart with the "snowflake" chart.

- Data labels would be at the point of each branch. (a.k.a bubbles around the edges that display the numbers.)
- the unique shape of this
- [https://chartjs-plugin-datalabels.netlify.app/samples/charts/polar.html](https://chartjs-plugin-datalabels.netlify.app/samples/charts/polar.html) for data labels inspiration 

![image](https://user-images.githubusercontent.com/108619510/184790249-e1b2a1a0-c313-431a-8fe0-2666bb6b3067.png)

**Comment by xiaohai-huang** [comment]
discard this issue because of the new mock up #25
