### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by FHFHockey-dev** [FHFHockey-dev/fhfhockey.com#4]
Make the website mobile friendly.

Below are things to consider:

- Header
- Banner
- Nav bar
- The padding on the left and right of the page

**Comment by xiaohai-huang** [comment]
The mobile UI design is needed.

**Comment by xiaohai-huang** [comment]
UI design 

![image](https://user-images.githubusercontent.com/56380096/178392638-7cbcc0cf-020b-41e4-8dd7-592edb5062a3.png)

![image](https://user-images.githubusercontent.com/56380096/178392845-f85b8325-9219-42b0-93dd-96b3599e96d1.png)
