### ISSUE TITLE
SEO: add html tags for better SEO performance

### ISSUE THREAD

**Issue by FHFHockey-dev** [FHFHockey-dev/fhfhockey.com#5]
Research on SEO and make the website SEO friendly.

- Test on [Twitter card](https://cards-dev.twitter.com/validator)

**Comment by xiaohai-huang** [comment]
This also include the `description` for each page

**Comment by FHFHockey** [comment]
I admittedly know nothing about SEO.  Can help with descriptions however

**Comment by xiaohai-huang** [comment]
> I admittedly know nothing about SEO. Can help with descriptions however

Can you provide the description for each page?
