### ISSUE TITLE
Add Blog

### ISSUE THREAD

**Issue by xiaohai-huang** [FHFHockey-dev/fhfhockey.com#6]
User requirements:

- I have a team of writers they can login, then have a text box with styling choices.
- publicly viewable, privately maintained and updated.

**Comment by xiaohai-huang** [comment]
UI design is needed. @FHFHockey-dev

**Comment by FHFHockey** [comment]
I can assist with the UI, or provide examples.

**Comment by xiaohai-huang** [comment]
Blog posts UI
![blog posts](https://user-images.githubusercontent.com/56380096/178419073-8e5c172c-1688-4929-9590-fb94006c5657.png)

**Comment by xiaohai-huang** [comment]
TJ: For the desktop blog it would be 2 cards length wise, same structure

**Comment by xiaohai-huang** [comment]
The whole blog card is clickable in both mobile and PC view.

![image](https://user-images.githubusercontent.com/56380096/178419536-9ac05915-262a-49d8-8f71-f849304bb3df.png)

**Comment by xiaohai-huang** [comment]
Need to know the font-family for Blog Post card

**Comment by xiaohai-huang** [comment]
New blog landing page

![image](https://user-images.githubusercontent.com/56380096/179361377-dbd60a68-27f2-4b9e-a695-9b2ffb1e8989.png)
